server:
  port: 9300
spring:
  application:
    name: service-shopping
  h2:
    console:
      enabled: true
  datasource:
    url: dbc:h2:mem:shoppingBD;
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect